AWSTemplateFormatVersion: "2010-09-09"
Description: Codepipeline Project

Parameters:
  project:
    Type: String
  environment:
    Type: String
    Description: Project's environment
    Default: dev
    AllowedValues:
      - dev
      - qa
      - prod
  service:
    Type: String
  artifactsBucketName:
    Type: String
  repositoryName:
    Type: String
  repositoryBranch:
    Type: String
    Default: main
  codePipelineRoleArn:
    Type: String
  gitConnectionArn:
    Type: String
  buildProjectName:
    Type: String
  deployService:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
  ecsClusterName:
    Type: String
  ecsServiceName:
    Type: String
  deploymentTimeout:
    Type: String
    Default: '10'
  automaticDeploy:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'
Conditions:
  doDeploy: !Equals 
    - !Ref deployService
    - 'true'
Resources:
  CodePipelineProject:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: !Sub ${project}-${environment}-${service}-pipeline
      ArtifactStore:
        Location: !Ref artifactsBucketName
        Type: S3
      RestartExecutionOnUpdate: False
      RoleArn: !Ref codePipelineRoleArn
      Stages: 
        - Name: Source
          Actions: 
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: 1
              Configuration:
                ConnectionArn: !Ref gitConnectionArn
                FullRepositoryId: !Ref repositoryName
                BranchName: !Ref repositoryBranch
                OutputArtifactFormat: "CODEBUILD_CLONE_REF"
                DetectChanges: !Ref automaticDeploy
              RunOrder: 1
              OutputArtifacts:
                - Name: Source
              Namespace: SourceVariables
        - Name: Build
          Actions: 
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName: !Ref buildProjectName
                EnvironmentVariables: 
                  !Sub |
                    [
                      {
                        "name": "ENVIRONMENT",
                        "value": "${environment}",
                        "type": "PLAINTEXT"
                      }
                    ]
              RunOrder: 1
              InputArtifacts:
                - Name: Source
              OutputArtifacts:
                - Name: Build
              Namespace: BuildVariables
        - !If
          - doDeploy
          - Name: Deploy
            Actions: 
              - Name: Deploy
                ActionTypeId:
                  Category: Deploy
                  Owner: AWS
                  Provider: ECS
                  Version: 1
                Configuration:
                  ClusterName: !Ref ecsClusterName
                  ServiceName: !Ref ecsServiceName
                  FileName: imagedefinitions.json
                  DeploymentTimeout: !Ref deploymentTimeout
                RunOrder: 1
                InputArtifacts:
                  - Name: Build
                Namespace: DeployVariables
          - !Ref AWS::NoValue
Outputs:
  codePipelineProjectName:
    Value: !Ref CodePipelineProject
  codePipelineProjectArn:
    Value: !Sub arn:aws:codepipeline:${AWS::Region}:${AWS::AccountId}:${CodePipelineProject}